import sys
import subprocess
from datetime import datetime
import webbrowser
import os

# Validate argument
if len(sys.argv) < 2:
    print("Usage:")
    print("python run_test.py <yaml_file>")
    sys.exit(1)

yaml_file = sys.argv[1]

print(f"Running: {yaml_file}")

# Start Time
start_time = datetime.now()

# Run Maestro
result = subprocess.run(
    ["maestro.cmd", "test", yaml_file],
    capture_output=True,
    text=True,
    shell=True
)

# End Time
end_time = datetime.now()

# Status
status = "PASS" if result.returncode == 0 else "FAIL"

# Create reports folder
os.makedirs("reports", exist_ok=True)

# Generate report name
test_name = os.path.splitext(os.path.basename(yaml_file))[0]

counter = 1

while True:
    report_path = os.path.join(
        "reports",
        f"{test_name}({counter}).html"
    )

    if not os.path.exists(report_path):
        break

    counter += 1

# HTML Report
html = f"""
<!DOCTYPE html>
<html>
<head>
<title>Maestro Automation Report</title>

<style>

* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

body {{
    font-family: Segoe UI, Arial, sans-serif;
    background-color: #f4f6f9;
    padding: 30px;
}}

.header {{
    background: linear-gradient(135deg, #4e73df, #224abe);
    color: white;
    padding: 25px;
    border-radius: 10px;
    margin-bottom: 25px;
}}

.card {{
    background: white;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0px 2px 10px rgba(0,0,0,0.1);
    margin-bottom: 20px;
}}

.status-pass {{
    color: green;
    font-weight: bold;
}}

.status-fail {{
    color: red;
    font-weight: bold;
}}

.info-grid {{
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 15px;
}}

.info-box {{
    background: #f8f9fc;
    padding: 15px;
    border-left: 5px solid #4e73df;
    border-radius: 5px;
}}

table {{
    width: 100%;
    border-collapse: collapse;
}}

th {{
    background: #4e73df;
    color: white;
    padding: 12px;
    text-align: left;
}}

td {{
    padding: 12px;
    border-bottom: 1px solid #ddd;
}}

pre {{
    background: #1e1e1e;
    color: #00ff88;
    padding: 15px;
    border-radius: 8px;
    overflow-x: auto;
    max-height: 500px;
}}

.footer {{
    text-align: center;
    margin-top: 20px;
    color: gray;
}}

</style>
</head>

<body>

<div class="header">
    <h1>📱 Maestro Automation Report</h1>
    <p>Execution Summary</p>
</div>

<div class="card">

    <div class="info-grid">

        <div class="info-box">
            <strong>Test Script</strong><br>
            {yaml_file}
        </div>

        <div class="info-box">
            <strong>Status</strong><br>
            <span class="{'status-pass' if status == 'PASS' else 'status-fail'}">
                {status}
            </span>
        </div>

        <div class="info-box">
            <strong>Start Time</strong><br>
            {start_time}
        </div>

        <div class="info-box">
            <strong>End Time</strong><br>
            {end_time}
        </div>

    </div>

</div>

<div class="card">

    <h2>Execution Details</h2>
    <br>

    <table>
        <tr>
            <th>Test Case</th>
            <th>Status</th>
        </tr>

        <tr>
            <td>{test_name}</td>
            <td>
                <span class="{'status-pass' if status == 'PASS' else 'status-fail'}">
                    {status}
                </span>
            </td>
        </tr>
    </table>

</div>

<div class="card">

    <h2>Execution Logs</h2>
    <br>

    <pre>
{result.stdout}

{result.stderr}
    </pre>

</div>

<div class="footer">
    Generated by Maestro Automation Framework
</div>

</body>
</html>
"""

# Save report
with open(report_path, "w", encoding="utf-8") as file:
    file.write(html)

print(f"Report Generated: {os.path.abspath(report_path)}")

# Open report automatically
webbrowser.open(os.path.abspath(report_path))