"""Builds the Markdown report used for the PR body and GitHub step summary.

Note: source is kept pure-ASCII; emoji are emitted via chr() codepoints.
"""

from __future__ import annotations

import difflib
import os
from pathlib import Path

from .fixer import HealRecord

E_BANDAGE = chr(0x1FA79)  # bandage emoji
E_CHECK = chr(0x2705)     # check mark
E_CROSS = chr(0x274C)     # cross mark


def _diffs(record: HealRecord) -> list[tuple[str, str]]:
    """(path, unified diff) for every file the heal changed."""
    out: list[tuple[str, str]] = []
    for path, final in record.finals.items():
        original = record.originals.get(path, "")
        if not final or final == original:
            continue
        diff = "".join(
            difflib.unified_diff(
                original.splitlines(keepends=True),
                final.splitlines(keepends=True),
                fromfile=f"a/{path}",
                tofile=f"b/{path}",
            )
        )
        if diff:
            out.append((path, diff))
    return out


def build_report(records: list[HealRecord], passed_first_try: list[str]) -> str:
    healed = [r for r in records if r.healed]
    unhealed = [r for r in records if not r.healed]

    lines = [f"# {E_BANDAGE} Maestro Self-Healing Report", ""]
    lines.append(
        f"**Summary:** {len(passed_first_try)} passed, "
        f"{len(healed)} auto-healed, {len(unhealed)} still failing."
    )
    lines.append("")

    if healed:
        lines.append(f"## {E_CHECK} Auto-healed flows")
        lines.append("")
        lines.append("| Flow | Changed files | Root cause | Fix | Attempts | Confidence |")
        lines.append("|---|---|---|---|---|---|")
        for r in healed:
            last = next((a for a in reversed(r.attempts) if a.accepted), None)
            changed = ", ".join(f"`{p}`" for p in r.finals) or f"`{r.flow}`"
            lines.append(
                f"| `{r.flow}` | {changed} | {_esc(last.root_cause if last else '')} | "
                f"{_esc(last.fix_description if last else '')} | {len(r.attempts)} | "
                f"{(last.confidence if last else 0):.0%} |"
            )
        lines.append("")
        for r in healed:
            for path, d in _diffs(r):
                lines.append(f"<details><summary>Diff: <code>{path}</code></summary>\n")
                lines.append(f"```diff\n{d}\n```\n</details>\n")

    if unhealed:
        lines.append(f"## {E_CROSS} Flows that could not be healed")
        lines.append("")
        for r in unhealed:
            lines.append(f"### `{r.flow}`")
            if r.unfixable_reason:
                lines.append(f"- Reason: {_esc(r.unfixable_reason)}")
            for a in r.attempts:
                outcome = a.rejection_reason or ("re-run still failed" if a.accepted else "rejected")
                lines.append(f"- Attempt {a.attempt}: {_esc(a.fix_description or a.root_cause)} - {outcome}")
            lines.append("")
        lines.append("> These need human attention. Check the workflow artifacts for full Maestro logs.")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by maestro-self-healing. All fixes were validated "
                 "(YAML parse, command whitelist, appId & assertion guardrails) and "
                 "re-run to green before being proposed. Nothing was pushed to your branch; "
                 "review this PR like any other._")
    return "\n".join(lines)


def write_report(report: str, path: str) -> None:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(report, encoding="utf-8")
    # Also surface in the GitHub Actions run summary if available.
    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with open(summary, "a", encoding="utf-8") as fh:
            fh.write(report + "\n")


def _esc(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ")
